[package]
name = "zz"
version = "0.1.0"
authors = ["Arvid E. Picciani <aep@exys.org>"]
edition = '2018'
license = "MIT"
description = "the zz language"
repository = "https://github.com/aep/zz"
readme = "README.md"

[dependencies]
pest = "2.1"
pest_derive = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml  = "0.5"
fasthash = "0.4.0"
clap = "2"
log = "0.4"
env_logger = "0.6"
